### ISSUE TITLE
Delayed exchange initialization

### ISSUE THREAD

**Issue by scionaltera** [agonyforge/arbitrader#151]
If an exchange is configured, but is in a blackout period when Arbitrader starts up, schedule initialization of the exchange when the blackout period is over. Dynamically add it to the rotation when it is up and running.

I think that if the exchange is not in a blackout but throws errors, stopping the bot is still the correct action to take. That indicates that the errors were unexpected and might need to be fixed by the operator: configuration problems, low account balance, wrong API keys, etc. The blackout period is something that has to be specifically configured (I generally set one up when the exchange emails me to warn about planned maintenance) and so we can reasonably assume that the broken exchange is known to be broken and should be ignored until the end of the blackout window.

**Comment by sanitariu** [comment]
Maybe stopping the bot is correct but in my case bitstamp was the first exchange and order was already placed and executed. Then bot crashes on second exchange because of exchange not working or maintenance mode. I think we should notify somehow that bot crashed and order was executed on the first exchange.
